import React, { createContext, useContext, useState, useCallback, useEffect } from "react";

export type Lang = "en" | "fr";

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
}

const translations: Record<Lang, Record<string, string>> = {
  en: {
    "nav.home": "Home",
    "nav.about": "About",
    "nav.programs": "Programs",
    "nav.projects": "Projects",
    "nav.blog": "Our Articles",
    "nav.team": "Team",
    "nav.contact": "Contact",
    "hero.title": "Advancing Freedom, Prosperity & a Greener Future",
    "hero.subtitle": "Centre for Green Development is a Burundi-based think tank strengthening economic literacy, promoting transparency, and championing market-based solutions for sustainable development.",
    "hero.cta": "Our Programs",
    "hero.cta2": "Learn More",
    "about.title": "About CGD",
    "about.mission.title": "Our Mission",
    "about.mission.text": "To advance freedom, prosperity, and a greener future by strengthening economic literacy, promoting transparency, and championing market-based solutions for sustainable development.",
    "about.vision.title": "Our Vision",
    "about.vision.text": "We envision a society where free and informed citizens shape sustainable development, environmental protection complements economic opportunity, and public institutions are transparent, accountable, and responsive. A society in which liberty and sustainability reinforce one another, generating lasting prosperity for present and future generations.",
    "about.history.title": "Our History",
    "about.history.text": "Founded in Burundi, Centre for Green Development was born from the conviction that economic freedom and environmental stewardship can go hand in hand. Since our inception, we have worked tirelessly to empower communities through education, policy advocacy, and innovative programs that bridge the gap between sustainable development and economic opportunity.",
    "about.approach.title": "Our Approach",
    "about.approach.research": "Research",
    "about.approach.research.desc": "We conduct rigorous, evidence-based research to inform policy decisions and public discourse on economic and environmental issues.",
    "about.approach.advocacy": "Advocacy",
    "about.approach.advocacy.desc": "We advocate for policies that promote transparency, accountability, and market-based solutions for sustainable development.",
    "about.approach.community": "Community Engagement",
    "about.approach.community.desc": "We empower communities through education, training, and direct engagement to build local capacity for sustainable development.",
    "about.values.title": "Our Values",
    "about.values.integrity": "Integrity",
    "about.values.integrity.desc": "We uphold the highest ethical standards in all our work and relationships.",
    "about.values.sustainability": "Sustainability",
    "about.values.sustainability.desc": "We champion solutions that balance economic growth with environmental stewardship.",
    "about.values.innovation": "Innovation",
    "about.values.innovation.desc": "We embrace creative, market-based approaches to solving complex development challenges.",
    "about.values.inclusion": "Inclusion",
    "about.values.inclusion.desc": "We believe in empowering all citizens, especially youth and marginalized communities.",
    "programs.title": "Our Programs",
    "programs.subtitle": "Driving change through research, advocacy, and community engagement.",
    "programs.learn": "Learn More",
    "team.title": "Our Team",
    "team.subtitle": "The people driving change at Centre for Green Development.",
    "contact.title": "Contact Us",
    "contact.subtitle": "Get in touch with Centre for Green Development.",
    "contact.address": "Address",
    "contact.phone": "Phone",
    "contact.email": "Email",
    "contact.send": "Send Message",
    "contact.name": "Your Name",
    "contact.message": "Your Message",
    "footer.rights": "All rights reserved.",
    "footer.tagline": "Let's bring together green revolution",
    "general.readmore": "Read More",
    "donate.title": "Donate",
    "donate.intro.title": "Support Our Mission",
    "donate.intro.text": "Your generous contribution helps us advance economic literacy, promote transparency, and champion sustainable development across Burundi and beyond.",
    "donate.holder": "Account Holder",
    "donate.account": "Account Number",
    "donate.other.title": "Other Ways to Give",
    "donate.thanks": "Every contribution, no matter how small, makes a difference. Thank you for believing in a greener, freer future for all. A receipt will be issued for every donation.",
    "hero.slide1.title": "Advancing Freedom, Prosperity & a Greener Future",
    "hero.slide1.subtitle": "Centre for Green Development is a Burundi-based think tank strengthening economic literacy, promoting transparency, and championing market-based solutions.",
    "hero.slide2.title": "Empowering Communities Through Knowledge",
    "hero.slide2.subtitle": "We equip citizens with the tools and understanding to drive sustainable change in their communities.",
    "hero.slide3.title": "Championing Transparency & Good Governance",
    "hero.slide3.subtitle": "Promoting accountability in public institutions through research, advocacy, and civic engagement.",
    "hero.slide4.title": "Building a Sustainable Tomorrow",
    "hero.slide4.subtitle": "Bridging economic opportunity and environmental stewardship for present and future generations.",
    "nav.partners": "Partners",
    "partners.intro": "We collaborate with organizations that share our vision for a greener, freer future. Together, we amplify our impact across Burundi and beyond.",
    "home.section.programs": "Flagship programs",
    "home.section.programs.kicker": "What we do",
    "home.section.projects": "Latest projects",
    "home.section.projects.kicker": "Tangible impact",
    "home.section.articles": "Our articles",
    "home.section.articles.kicker": "Blog & news",
    "home.section.testimonials": "What they say about us",
    "home.section.testimonials.kicker": "Testimonials",
    "home.section.testimonials.sub": "Voices of those who benefited from our work.",
    "home.section.partners.kicker": "They trust us",
    "home.section.viewall": "View all",
    "general.learnmore": "Learn more",
    "general.donate": "Donate",
    "general.contact": "Contact us",
  },
  fr: {
    "nav.home": "Accueil",
    "nav.about": "À propos",
    "nav.programs": "Programmes",
    "nav.projects": "Projets",
    "nav.blog": "Nos Articles",
    "nav.team": "Équipe",
    "nav.contact": "Contact",
    "hero.title": "Promouvoir la liberté, la prospérité et un avenir plus vert",
    "hero.subtitle": "Le Centre pour le Développement Vert est un think tank basé au Burundi qui renforce la culture économique, promeut la transparence et défend les solutions basées sur le marché pour le développement durable.",
    "hero.cta": "Nos Programmes",
    "hero.cta2": "En savoir plus",
    "about.title": "À propos du CGD",
    "about.mission.title": "Notre Mission",
    "about.mission.text": "Promouvoir la liberté, la prospérité et un avenir plus vert en renforçant la culture économique, en promouvant la transparence et en défendant les solutions basées sur le marché pour le développement durable.",
    "about.vision.title": "Notre Vision",
    "about.vision.text": "Nous envisageons une société où des citoyens libres et informés façonnent le développement durable, où la protection de l'environnement complète les opportunités économiques, et où les institutions publiques sont transparentes, responsables et réactives.",
    "about.history.title": "Notre Histoire",
    "about.history.text": "Fondé au Burundi, le Centre pour le Développement Vert est né de la conviction que la liberté économique et la gestion environnementale peuvent aller de pair. Depuis notre création, nous avons travaillé sans relâche pour autonomiser les communautés par l'éducation, le plaidoyer politique et des programmes innovants qui comblent le fossé entre le développement durable et les opportunités économiques.",
    "about.approach.title": "Notre Approche",
    "about.approach.research": "Recherche",
    "about.approach.research.desc": "Nous menons des recherches rigoureuses et fondées sur des preuves pour éclairer les décisions politiques et le discours public.",
    "about.approach.advocacy": "Plaidoyer",
    "about.approach.advocacy.desc": "Nous plaidons pour des politiques qui promeuvent la transparence, la responsabilité et les solutions basées sur le marché.",
    "about.approach.community": "Engagement communautaire",
    "about.approach.community.desc": "Nous autonomisons les communautés par l'éducation, la formation et l'engagement direct.",
    "about.values.title": "Nos Valeurs",
    "about.values.integrity": "Intégrité",
    "about.values.integrity.desc": "Nous maintenons les plus hauts standards éthiques dans tout notre travail et nos relations.",
    "about.values.sustainability": "Durabilité",
    "about.values.sustainability.desc": "Nous défendons des solutions qui équilibrent la croissance économique et la gestion environnementale.",
    "about.values.innovation": "Innovation",
    "about.values.innovation.desc": "Nous adoptons des approches créatives et basées sur le marché pour résoudre les défis complexes du développement.",
    "about.values.inclusion": "Inclusion",
    "about.values.inclusion.desc": "Nous croyons en l'autonomisation de tous les citoyens, en particulier les jeunes et les communautés marginalisées.",
    "programs.title": "Nos Programmes",
    "programs.subtitle": "Conduire le changement par la recherche, le plaidoyer et l'engagement communautaire.",
    "programs.learn": "En savoir plus",
    "team.title": "Notre Équipe",
    "team.subtitle": "Les personnes qui conduisent le changement au Centre pour le Développement Vert.",
    "contact.title": "Contactez-nous",
    "contact.subtitle": "Prenez contact avec le Centre pour le Développement Vert.",
    "contact.address": "Adresse",
    "contact.phone": "Téléphone",
    "contact.email": "E-mail",
    "contact.send": "Envoyer le message",
    "contact.name": "Votre Nom",
    "contact.message": "Votre Message",
    "footer.rights": "Tous droits réservés.",
    "footer.tagline": "Ensemble pour la révolution verte",
    "general.readmore": "Lire la suite",
    "donate.title": "Faire un don",
    "donate.intro.title": "Soutenez notre mission",
    "donate.intro.text": "Votre généreuse contribution nous aide à promouvoir la culture économique, la transparence et le développement durable au Burundi et au-delà.",
    "donate.holder": "Titulaire du compte",
    "donate.account": "Numéro de compte",
    "donate.other.title": "Autres moyens de donner",
    "donate.thanks": "Chaque contribution, aussi petite soit-elle, fait la différence. Merci de croire en un avenir plus vert et plus libre pour tous. Un reçu sera émis pour chaque don.",
    "hero.slide1.title": "Promouvoir la liberté, la prospérité et un avenir plus vert",
    "hero.slide1.subtitle": "Le Centre pour le Développement Vert renforce la culture économique, promeut la transparence et défend les solutions basées sur le marché.",
    "hero.slide2.title": "Autonomiser les communautés par le savoir",
    "hero.slide2.subtitle": "Nous équipons les citoyens des outils et de la compréhension nécessaires pour conduire un changement durable.",
    "hero.slide3.title": "Défendre la transparence et la bonne gouvernance",
    "hero.slide3.subtitle": "Promouvoir la responsabilité dans les institutions publiques par la recherche, le plaidoyer et l'engagement civique.",
    "hero.slide4.title": "Construire un demain durable",
    "hero.slide4.subtitle": "Relier opportunités économiques et gestion environnementale pour les générations présentes et futures.",
    "nav.partners": "Partenaires",
    "partners.intro": "Nous collaborons avec des organisations qui partagent notre vision d'un avenir plus vert et plus libre. Ensemble, nous amplifions notre impact au Burundi et au-delà.",
    "home.section.programs": "Programmes phares",
    "home.section.programs.kicker": "Ce que nous faisons",
    "home.section.projects": "Derniers projets",
    "home.section.projects.kicker": "Impact concret",
    "home.section.articles": "Nos articles",
    "home.section.articles.kicker": "Blog & Actualités",
    "home.section.testimonials": "Ce qu'ils disent de nous",
    "home.section.testimonials.kicker": "Témoignages",
    "home.section.testimonials.sub": "Les voix de ceux qui ont bénéficié de nos actions.",
    "home.section.partners.kicker": "Ils nous font confiance",
    "home.section.viewall": "Voir tout",
    "general.learnmore": "En savoir plus",
    "general.donate": "Faire un don",
    "general.contact": "Nous contacter",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLangState] = useState<Lang>(() => {
    if (typeof window === "undefined") return "en";
    const saved = window.localStorage.getItem("lang");
    return saved === "en" || saved === "fr" ? saved : "en";
  });
  const setLang = useCallback((l: Lang) => {
    setLangState(l);
    try { window.localStorage.setItem("lang", l); } catch {}
  }, []);
  useEffect(() => { document.documentElement.lang = lang; }, [lang]);
  const t = useCallback((key: string) => translations[lang][key] || key, [lang]);
  return <LanguageContext.Provider value={{ lang, setLang, t }}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};
